#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 10 00:12:05 2021

@author: mizo
"""

import numpy as np

A=np.zeros((30,230))
k=0
for i in range(10) :
        for j in range(20):
            A[i,j*10+k]=1.0
        k+=1
        
for i in range(10) :
    A[i,i+200]=-1.

for i in range(20) :
        for j in range(10):
            A[i+10,i*10+j]=1.0
        
for i in range(20) :
    A[i+10,i+210]=1.0



print(A)
A2=A.transpose()

A=np.zeros((7,19))
k=0
for i in range(3) :
        for j in range(4):
            A[i,j*3+k]=1.0
        k+=1
        
for i in range(3) :
    A[i,i+12]=-1.

for i in range(4) :
        for j in range(3):
            A[i+3,i*3+j]=1.0
        
for i in range(4) :
    A[i+3,i+15]=1.0