#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 15 09:36:36 2022

@author: Mizo
"""

#First challenge Python programing assessment :
import math

while True:
    try:
        a = str(input('a: '))
        if not isinstance(a, str) :
            raise ValueError #this will send it to the print message and back to the input option
        break
    except ValueError:
        print("print not str")

while True:
    try:
        b = str(input('b: '))
        if not isinstance(a, str) :
            raise ValueError #this will send it to the print message and back to the input option
        break
    except ValueError:
        print("print not str")

while True:
    try:
        l = int(input('l: '))
        if l < 5 or l > 200 or not isinstance(l, int) :
            raise ValueError #this will send it to the print message and back to the input option
        break
    except ValueError:
        print("res1")

while True:
    try:
        prog = float(input('prog: '))
        if prog< 0 or prog > 1 or not isinstance(prog, float) :
            raise ValueError #this will send it to the print message and back to the input option
        break
    except ValueError:
        print("res2")


a_rep=0
brep=0
output=""
a_rep=math.ceil(l*prog)
brep=l-a_rep
for i in range(a_rep):
    output=output+a
for i in range(brep):
    output=output+b
print(output)