#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 15 11:31:57 2022

@author: mizo
"""

t='Ilv oig!ndceo '
l=[]
output=""
for a in t:

    l.append(a)
while len(l)>0:

    output=output+str(l.pop(0))
    try :
        output=output+str(l.pop(-1))
    except:
        continue
    
print(output)